Improvement/day1/refactoring into functions
jkelly282/Advent-of-code pull request #3
Opened 2019-02-14 09:36 UTC by jkelly282

2019-02-14 11:00 UTC, GvandeSteeg requested changes
Functions could use some docstrings, and I'd like to see unit tests for day1_extra 🥇

2019-02-14 11:00 UTC, GvandeSteeg commented on day1/day1_extra.py
> +def open_file(filepath):
I'd recommend to merge the two files, or at least import from `day1.py` instead of duplicating code

2019-02-14 11:00 UTC, GvandeSteeg commented on day1/day1_extra.py
> +    while True:
```suggestion
while not solved:
```

2019-02-14 11:00 UTC, GvandeSteeg commented on day1/day1_extra.py
> +                break
```suggestion
```

2019-02-14 11:00 UTC, GvandeSteeg commented on day1/day1_extra.py
> +        if solved:
```suggestion
```

2019-02-14 11:00 UTC, GvandeSteeg commented on day1/day1_extra.py
> +            break
```suggestion
```

2019-02-14 11:00 UTC, GvandeSteeg commented on day1/day1_extra.py
> +            break
ok, the new feature is cool but only for single lines..

basically, you can get rid of ```if solved: break``` if you put `solved` as the `while` condition

2019-02-14 11:00 UTC, GvandeSteeg commented on day2/Day 2.py
> +# Storing the letters of the alphabet into a variable
When working on day 2, switch back to `master` first, then `create new branch` and work/commit/push your day2 stuff to that branch. Now you've got a PR with 2 'features'

2019-02-15 11:06 UTC, merged

2019-02-18 15:17 UTC, jkelly282 commented on day1/day1_extra.py
> +def open_file(filepath):
Day 2 requires string parsing not int parsing in the method ? Does this make a difference ?

2019-02-18 17:07 UTC, GvandeSteeg commented on day1/day1_extra.py
> +def open_file(filepath):
merge day1 and day1 extra, not day 1 and day2. You can either refactor the open_file from day1 into two separate functions, or write a new file opener for day2